daily/urls.py
from django.urls import path
from .views import *
from django.contrib.auth import views as auth_views
from daily import views

app_name = "daily"

urlpatterns = [
    #path('', views.index, name='index'),
    path('<int:daily_id>/', DailyDetail.as_view(), name="detail"),
    path('upload/', DailyUpload.as_view(), name="upload"),
    path('action/', UserToDailyAction.as_view(), name="action"),
    path('like/', UserToDailyLike.as_view(), name="like"),
    path('update/<int:id>/', DailyDetailUpdate.as_view(), name="update"),
    path('delete/<int:id>/', DailyDetailDelete.as_view(), name="delete"),
    path('replydelete/<int:id>/', ReplyDelete.as_view(), name="replydelete"),
    path('daily/<int:id>/', DailyDetail.as_view(), name="daily"),
    path('reply/<int:id>/', ReplyCreate.as_view(), name="reply"),
]

studyProject/urls.py
from django.contrib import admin
from django.urls import path, include
from pashion import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "main"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.main, name='main'),
    path('weather/', views.weather, name='weather'),
    path('user/', include('user.urls', namespace="user")),
    path('daily/', include('daily.urls', namespace="daily")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from .views import *
from django.contrib.auth import views as auth_views

app_name = "user"

urlpatterns = [
    path('regist/', Regist.as_view(), name="regist"),
    path('login/', Login.as_view(), name="login"),
    path('logout/', Logout.as_view(), name="logout"),
    path('profile/<str:id>/', Profile.as_view(), name="profile"),
    path('profile_update/', Profile_update.as_view(), name="profile_update")

]

daily/models.py
from django.db import models
from user.models import User

# 데일리 게시글 모델


class Daily(models.Model):
    # 게시자 ID
    user_id = models.ForeignKey(
        User, db_column='user_id', on_delete=models.CASCADE)

    # 게시글 이미지
    daily_image = models.ImageField(
        null=True, upload_to='images/', blank=True)

    # 게시글 내용
    content = models.TextField()

    # 읽은 수
    read = models.IntegerField(default=0)

    # 게시일
    create_day = models.DateTimeField(auto_now_add=True)

    # 수정일
    update_day = models.DateTimeField(auto_now=True)

    # 스타일 태그
    style_tag = models.TextField(null=True, blank=True)

    def __str__(self):
        return ''

# 북마크 / 좋아요 남긴 게시글 ( 추후 통합 필요 )
class Bookmark(models.Model):
    # 유저 ID
    user_id = models.ForeignKey(
        User, db_column='user_id', on_delete=models.CASCADE)

    # 게시글 번호
    daily_id = models.ForeignKey(
        Daily, db_column='daily_id', on_delete=models.CASCADE)


class DailyLike(models.Model):
    # 유저 ID
    user_id = models.ForeignKey(
        User, db_column='user_id', on_delete=models.CASCADE)

    # 게시글 번호
    daily_id = models.ForeignKey(
        Daily, db_column='daily_id', on_delete=models.CASCADE)

# 데일리 게시글 댓글 모델


class DailyReply(models.Model):
    # 유저 ID
    user_id = models.ForeignKey(
        User, db_column='user_id', on_delete=models.CASCADE)

    # 게시글 번호
    daily_id = models.ForeignKey(
        Daily, db_column='daily_id', on_delete=models.CASCADE)

    # 내용
    content = models.TextField(null=False, blank=False)

    # 작성일
    create_day = models.DateTimeField(auto_now_add=True)

    # 수정일
    update_day = models.DateTimeField(auto_now=True)

    # 원댓글 번호
    ref = models.IntegerField()

    # 대댓글 번호
    ref_num = models.IntegerField(default=1)

daily/forms.py
from django import forms
from user.models import User
from .models import *


class DailyForm(forms.ModelForm):
    class Meta:
        model = Daily
        fields = ['content', 'daily_image', 'style_tag', 'user_id']


class BookmarkForm(forms.ModelForm):
    class Meta:
        model = Bookmark
        fields = ['daily_id', 'user_id']


class DailyLikeForm(forms.ModelForm):
    class Meta:
        model = DailyLike
        fields = ['daily_id', 'user_id']

class DailyReplyForm(forms.ModelForm):
    class Meta:
        model = DailyReply
        fields = ['daily_id', 'user_id', 'content']

daily/views.py
import json
from django.views import View
from django.http import JsonResponse
from django.shortcuts import *
from .models import *
from .forms import *
from datetime import datetime
from django.contrib.auth import authenticate
from studyProject.util import *
from studyProject.common import *
from studyProject.decorate import *

# Create your views here.


class DailyDetail(View):
    def get(self, request, daily_id):
        data = request.GET
        if(Daily.objects.filter(id=daily_id).exists() == False):
            return ErrorMsg("존재하지 않는 게시글입니다.", "main.html")

        daily = Daily.objects.get(id=daily_id)
        reply = DailyReply.objects.filter(
            daily_id=daily_id).order_by('ref', 'ref_num')
        return render(request, 'daily/post.html', {'daily': daily, 'reply': reply})

class DailyUpload(View):
    @LoginAuth
    def post(self, request):
        form = DailyForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('/')
        else:
            return render(request, 'daily/upload.html', {'form': form})

    def get(self, request):
        data = request.GET
        form = DailyForm(data)
        return render(request, 'daily/upload.html', {'form': form})

# ajax 요청


class UserToDailyAction(View):
    def post(self, request):
        return ErrorMsg("올바르지 않은 접근입니다.", "main")

    @LoginAuth
    def get(self, request):
        data = request.GET
        login_id = request.session.get('login_id')

        if(data['action'] == 'like'):
            Object = DailyLike
        else:
            Object = Bookmark

        if Object.objects.filter(user_id=login_id, daily_id=data['daily_id']).exists():
            Object\
                .objects\
                .get(
                    user_id=login_id, daily_id=data['daily_id']
                ).delete()
        else:
            Object.objects.create(
                user_id=User.objects.get(id=login_id),
                daily_id=Daily.objects.get(id=data['daily_id']),
            )

        count = DailyLike.objects.filter(daily_id=data['daily_id']).count()
        return HttpResponse("|||SUCCESS|||" + str(count))


class UserToDailyLike(View):
    @LoginAuth
    def get(self, request):
        return render(request, 'daily/like.html')

class DailyDetailUpdate(View):
    @LoginAuth
    def post(self, request):
        form = DailyForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('/')
        else:
            return render(request, 'daily/update.html', {'form': form})

    def get(self, request, id):
        daily = Daily.objects.get(id=id)
        data = request.GET
        form = DailyForm(instance=daily)
        return render(request, 'daily/update.html', {'form': form})

class DailyDetailDelete(View):
    def get(self, request, id):
        daily = Daily.objects.get(id=id)
        daily.delete()
        return redirect("/")

class ReplyCreate(View):
    @LoginAuth
    def post(self, request, id):
        data = request.POST
        if 'ref' in data and data['ref']:
            ref_num = DailyReply.objects.filter(
                daily_id=id, ref=data['ref']).count() + 1
            ref = data['ref']
        else:
            ref_num = 1
            ref = DailyReply.objects.filter(daily_id=id).count() + 1

        reply = DailyReply(
            daily_id=Daily.objects.get(id=id),
            content=data['content'],
            user_id=User.objects.get(id=request.session.get('login_id')),
            ref=ref,
            ref_num=ref_num
        )

        reply.save()
        return redirect("/daily/" + str(id))


class ReplyDelete(View):
    def get(self, request, id):
        reply = DailyReply.objects.get(pk=id)
        reply.delete()
        return redirect("/daily/" + str(reply.daily_id.id))

daily/templates/daily/heart.html
{% extends "base.html" %}
{% block content %}

<html>
<p>찜목록 ㅇㅅㅇ</p>
</html>
{% endblock content %}

daily/templates/daily/like.html
{% extends "base.html" %}
{% block content %}
<p> 찜 목록  </p>
{% endblock content %}

daily/templates/daily/messenger.html
{% extends "base.html" %}
{% block content %}
<p> 메신저 목록  </p>
{% endblock content %}

daily/templates/daily/post.html
{% extends "base.html" %}
<!-- {% block title %} {{ id }} 회원의 데일리 포스트 {% endblock %} -->
{% block content %}
<div class="container">
    <div id="designer" class="row featurette">
        <div class="col-md-6">
            <h2 class="featurette-heading">{{ daily.user_id.id }}<span id="namedeco" class="text-muted">회원의 포스트</span>
            </h2>
            <h5 class="featurette-heading">{{ daily.content }}</h5>
            <p class="lead"># {{ daily.style_tag }}</p>

            {% if request.session.login_id == daily.user_id.id %}
            <div class="d-flex justify-content between align-items-center">
                <div class="btn-group">
                    <a href="{% url 'daily:update' daily.id %}" class="btn btn-sm btn-outline-primary"><i class="fas fa-pencil-alt"></i></a>
                    <a href="{% url 'daily:delete' daily.id %}" class="btn btn-sm btn-outline-danger"><i class="fas fa-trash-alt"></i></a>
                </div>
            </div>
            {% endif %}
        </div>
        <div class="col-md-4">
            <img src="/media/{{ daily.daily_image }}" width="150%" alt="daily_image">
        </div>
    </div>
    <hr>

    <form method="POST" action="{% url 'daily:reply' daily.id %}">
        {% csrf_token %}
        <input type="hidden" id="ref" name="ref" />
        <div class="row page-header">
            {% if request.session.login_id %}
            <div class="reply-input" id="reply_form">
                <input type="text" id="content" name="content">
                <button type="submit">작성</button>
            </div>
            {% endif %}

            {% for re in reply %}
            <div class="col-lg-12 reply-content mt-2 text-white">
                <div class="col-lg-2 float-left">{{ re.user_id.nickname }}</div>
                <div class="col-lg-6 float-left">
                    {% if re.ref_num > 1 %}ㄴ{% endif %}
                    {{ re.content | linebreaksbr | truncatechars:100 }}
                </div>
                <div class="col-lg-4 float-left">{{ re.create_day }}&nbsp;&nbsp;
                    {% if request.session.login_id == re.user_id.id or request.session.login_id == daily.user_id.id %}
                    <a href="{% url 'daily:replydelete' re.id %}" class="btn btn-sm btn-outline-danger float-right"><i
                            class="fas fa-trash-alt"></i></a>
                    {% endif %}

                    {% if request.session.login_id and re.ref_num == 1 %}
                    <a class="btn btn-sm btn-outline-danger float-right mr-2" onclick="Click(this, '{{ re.ref }}')"><i
                            class="fas fa-reply fa-rotate-180"></i></a>
                    {% endif %}
                </div>
            </div>
            <hr>
            {% endfor %}

        </div>
    </form>
</div>
<script>
    function Click(obj, ref) {
        var detach = $("#reply_form").detach();
        $(obj).parent().parent().after(detach);
        if (ref != undefined) {
            $("#ref").val(ref);
        }
    }
</script>
{% endblock content %}

daily/templates/daily/update.html
{% extends 'base.html' %}
{% block content %}
<div class="bs-docs-section clearfix">
    <div class="row mb-3 p-3 bg-light col-lg-4">
        <form class="post-form" action="{% url 'daily:upload' %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <input type="hidden" name="user_id" value="{{ request.session.login_id }}">

            <div class="form-group">
                <label for="id_content">게시글내용</label>
                <input type="text" class="form-control" name="content" id="id_content" value="{{ form.content }}">
            </div>

            <div class="form-group">
                <div>{% if daily.daily_image %}<p>등록된 이미지 : <a href="{{ daily.daily_image }}"
                            alt="daily_image">{{ daily.daily_image.url }}</a>
                    </p>{% endif %}</div>
                <p>새로운 이미지 : <input type="file" name="daily_image" accept="image/*" id="id_daily_image"></p>
            </div>

            <div class="form-group">
                <label for="id_style_tag">스타일태그</label>
                <input type="text" class="form-control" name="style_tag" id="id_style_tag" value="{{ form.style_tag }}">
            </div>

            <button type="submit" class="btn btn-outline-info btn-block float-left rounded">게시글 작성</button>
        </form>
    </div>
</div>
{% endblock %}

daily/templates/daily/upload.html
{% extends "base.html" %}
{% block content %}
<div class="bs-docs-section clearfix">
    <div class="row mb-3 p-3 bg-light col-lg-4">
        <form class="post-form" action="{% url 'daily:upload' %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <input type="hidden" name="user_id" value="{{ request.session.login_id }}">

            <div class="form-group">
                <label for="id_content">게시글내용</label>
                <input type="text" class="form-control" name="content" id="id_content">
            </div>

            <div class="form-group">
                <label for="daily_image">이미지</label>
                <input type="file" name="daily_image" accept="image/*" id="id_daily_image">
            </div>

            <div class="form-group">
                <label for="id_style_tag">스타일태그</label>
                <input type="text" class="form-control" name="style_tag" id="id_style_tag">
            </div>

            <button type="submit" class="btn btn-outline-info btn-block float-left rounded">게시글 작성</button>
        </form>
    </div>
</div>
{% endblock content %}