daily/urls.py
from django.urls import path
from .views import *
from django.contrib.auth import views as auth_views
from daily import views

app_name = "daily"

urlpatterns = [
    #path('', views.index, name='index'),
    path('<int:daily_id>/', DailyDetail.as_view(), name="detail"),
    path('upload/', DailyUpload.as_view(), name="upload"),
    path('action/', UserToDailyAction.as_view(), name="action"),
    path('like/', UserToDailyLike.as_view(), name="like"),
    path('update/<int:id>/', DailyDetailUpdate.as_view(), name="update"),
    path('delete/<int:id>/', DailyDetailDelete.as_view(), name="delete"),
    path('replydelete/<int:id>/', ReplyDelete.as_view(), name="replydelete"),
    path('daily/<int:id>/', DailyDetail.as_view(), name="daily"),
    path('reply/<int:id>/', ReplyCreate.as_view(), name="reply"),
]

studyProject/urls.py
from django.contrib import admin
from django.urls import path, include
from pashion import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "main"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.main, name='main'),
    path('weather/', views.weather, name='weather'),
    path('user/', include('user.urls', namespace="user")),
    path('daily/', include('daily.urls', namespace="daily")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from .views import *
from django.contrib.auth import views as auth_views

app_name = "user"

urlpatterns = [
    path('regist/', Regist.as_view(), name="regist"),
    path('login/', Login.as_view(), name="login"),
    path('logout/', Logout.as_view(), name="logout"),
    path('profile/<str:id>/', Profile.as_view(), name="profile"),
    path('profile_update/', Profile_update.as_view(), name="profile_update")

]

pashion/models.py
from django.db import models

# Create your models here.

pashion/views.py
from django.shortcuts import render, get_object_or_404
from django.http import JsonResponse
from studyProject import settings
from studyProject.common import *
from daily.models import *
from daily.forms import *

from user.models import *
from user.forms import *

# Create your views here.


def main(request):
    data = {}
    # 데일리 게시글
    daily_query = '''
        SELECT
            A.*
            , (SELECT COUNT(*) FROM daily_dailylike B WHERE A.id = B.daily_id) AS like
            , (SELECT COUNT(*) FROM daily_bookmark B WHERE A.id = B.daily_id) AS bookmark
            , (SELECT COUNT(*) FROM daily_dailyreply B WHERE A.id = B.daily_id) AS reply
        FROM 
            daily_daily A
        ORDER BY A.create_day DESC
    '''
    data["Daily"] = Daily.objects.raw(daily_query)[:6]
    data["DailyForm"] = DailyForm()

    return render(request, "main.html", data)


# 현재 위치 날씨 정보
def weather(request):
    data = request.GET
    print(data)
    param = {
        'lat': data.get('lat'),
        'lon': data.get('lon'),
        'appid': settings.WEATHER_KEY,
        'lang': 'kr',
    }
    weather_data = JsonAPIRequest('http://api.openweathermap.org/data/2.5/weather', param, 'GET')
    return JsonResponse({'data': weather_data}, status = 200)

def profile(request):
    return render(request, 'profile.html')


def daily_like(request):
    return render(request, 'like.html')

pashion/templates/base.html
{% load static %}

<!doctype html>
<html lang="en">

<head>
    <!-- font awesome -->
    <script src="https://kit.fontawesome.com/5b3cbd68ef.js" crossorigin="anonymous"></script>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- font-awesome -->
    <script src="https://kit.fontawesome.com/3c72f97009.js" crossorigin="anonymous"></script>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <!-- CSS -->
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/blog.css' %}">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link rel="stylesheet" href="{% static 'css/weather-icons-wind.css' %}">
    <link rel="stylesheet" href="{% static 'css/weather-icons.css' %}">
    <link rel="stylesheet" href="{% static 'css/googleapi.css' %}" type="text/css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <!-- jQuery and JS bundle w/ Popper.js -->
    <script src="https://code.jquery.com/jquery-3.4.1.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
        crossorigin="anonymous"></script>

    <!-- kakao map API -->
    <script type="text/javascript" src="//dapi.kakao.com/v2/maps/sdk.js?appkey=a2c1713f870b3a734ceaf135edd8c41b"></script>

    <!-- Common, Custom -->
    <script src="{% static 'js/common.js' %}/?t={% now 'ymdGHs'%}"></script>
    <script src="{% static 'js/custom.js' %}/?t={% now 'ymdGHs'%}"></script>

    <title>Django Project!</title>
</head>


<body>
    <!-- Nav bar -->
    <div class="navbar navbar-expand-lg fixed-top navbar-dark bg-dark">
        <div class="container">
            <h1><a href="/" class="navbar-brand">Toy project</a></h1>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>

        <!-- 로그인 된 경우 마이페이지/로그아웃 표시 -->
        {% if request.session.login_id %}
        <div class="float-right">
            <a href="/user/profile/{{request.session.login_id}}" style="margin-right: 5px;">
                {{ request.session.login_id }} 님
            </a>
            <a href="{% url 'user:logout' %}" style="margin-right: 5px;">
                <button class="btn btn-sm btn-primary">
                    <!-- <i class="fas fa-sign-out-alt"></i> -->
                    로그아웃
                </button>
            </a>
            <a href="{% url 'daily:upload' %}" style="margin-right: 5px;">
                <button class="btn btn-sm btn-primary">
                    <i class="fas fa-plus"></i>
                </button>
            </a>
            <a href="{% url 'daily:like' %}" style="margin-right: 5px;">
                <button class="btn btn-sm btn-primary">
                    <i class="fas fa-heart"></i>
                </button>
            </a>
            <a href="#" style="margin-right: 5px;">
                <button class="btn btn-sm btn-primary">
                    <i class="fas fa-comment"></i>
                </button>
            </a>
            <div>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <input type="text" placeholder="Search" class="header__search__input u-input-reset" value="" name="s"
                    id="s" />
                <button type="submit" onclick="alert('검색어를 입력하세요!')"><i class="fa fa-search"></i></button>
            </div>
            {% else %}
            <div>
                <a href="{% url 'user:login' %}" style="margin-right: 5px;">
                    <input type="button" class="btn btn-sm btn-primary" value="로그인">
                </a>

                <a href="{% url 'user:regist' %}" style="margin-right: 5px;">
                    <input type="button" class="btn btn-sm btn-info" value="회원가입">
                </a>
            </div>
            {% endif %}
        </div>
    </div>
    <div class="container">
        {% block content %}
        {% endblock content %}

    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous">
        </script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous">
        </script>

    <footer id="footer" class="bg-dark">
        <div class="row footer">
            <div class="col-lg-12">
                <p>Made by 강다예 / 유준혁 / 정지원</a>.</p>
                <p><a href="https://github.com/J511Y/Django">Code released github</a>.</p>
                <p>Based on <a href="https://getbootstrap.com" rel="nofollow">Bootstrap</a>. Icons from <a
                        href="https://fontawesome.com/" rel="nofollow">Font Awesome</a>. Web fonts from <a
                        href="https://fonts.google.com/" rel="nofollow">Google</a>.</p>

            </div>
        </div>
    </footer>
</body>

</html>

pashion/templates/error.html
{% extends "base.html" %}
{% block content %}

<div class="page-header">
    <div class="row">
        <div class="alert alert-danger col-lg-12" role="alert">
            <h4 class="alert-heading">에러가 발생했습니다!</h4>
            <p>{{ msg }}</p>
            {% if url %}
            <button class="btn btn-primary" onclick="location.href='/{{url}}'">>> 이동하기</button>
            {% endif %}
            <hr>
            <p class="mb-0">문의 연락처 : 010-8817-1849</p>
        </div>
    </div>
</div>

{% endblock content %}

pashion/templates/main.html
{% extends "base.html" %}
{% block content %}

<div class="jumbotron bg-light">
    <h1 class="display-4">
        <text id="weather_location"></text>
        <i id="weather_icon" class="wi float-right"></i>
    </h1>
    <hr>
    <h4 class="display-6">
        <div class="float-left col-lg-6">
            <text id="weather_temp"></text>
            <i class="wi wi-celsius"></i>
            &nbsp;/&nbsp;
            <text id="weather_feel_temp"></text>
            <i class="wi wi-celsius"></i>
        </div>
        
        <div class="float-left col-lg-3">
            <text id="weather_humidity"></text>
            <i class="wi wi-humidity"></i>
        </div>

        <div class="float-left col-lg-3">
            <text id="weather_wind"></text>
            <i class="wi wi-strong-wind"></i>
        </div>
    </h4>
</div>
<hr>
<script>
    $(document).ready(function(){
        var reqInfo = new Common.RequestInfo();
        reqInfo.AddParameter("lat", Navi.lat);
        reqInfo.AddParameter("lon", Navi.lon);

        Common.Ajax("weather/", reqInfo, function(rtn){
            console.log(rtn);
            Weather = Object.assign(Weather, JSON.parse(rtn));

            $("#weather_icon").addClass(Weather.getIconClass());
            $("#weather_icon").text(Weather.data.weather[0].description);
            $("#weather_location").text(" " + Weather.data.name);

            $("#weather_temp").text("현재 온도:" + parseInt(Weather.data.main.temp - 273));
            $("#weather_feel_temp").text("체감 온도:" + parseInt(Weather.data.main.feels_like - 273));

            $("#weather_humidity").text("습도:" + parseInt(Weather.data.main.humidity));
            
            $("#weather_wind").text("풍속:" + Weather.data.wind.speed);
        }, { 'formMethod': "GET" })
    })
</script>
<div class="page-header" id="banner">
    <div class="row">
        {% for daily in Daily %}
        <div class="card bg-light mb-3 col-lg-4 p-0" style="min-height: 18rem;">
            <div class="card-body daily-card"
                style="background-image: url('media/{{ daily.daily_image }}'); background-size:cover; cursor: pointer;"
                onclick="location.href='daily/{{ daily.id }}'">
                <p class="card-text text-white">{{ daily.content }}</p>
            </div>
            <div class="card-footer daily-card-footer">
                <div class="col-lg-3 float-left text-center text-primary" role="button"
                    onclick="DailyClick('like', '{{ daily.id }}');">
                    <i class="far fa-thumbs-up"></i>
                    <text id="daily_like_{{ daily.id }}">{{ daily.like }}</text>
                </div>
                <div class="col-lg-3 float-left text-center text-info" role="button">
                    <i class="fab fa-readme"></i>
                    <text id="daily_read_{{ daily.id }}">{{ daily.read }}</text>
                </div>
                <div class="col-lg-3 float-left text-center text-danger" role="button"
                    onclick="DailyClick('bookmark', '{{ daily.id }}');">
                    <i class="fas fa-bookmark"></i>
                    <text id="daily_bookmark_{{ daily.id }}">{{ daily.bookmark }}</text>
                </div>
                <div class="col-lg-3 float-left text-center text-dark" role="button">
                    <i class="far fa-comment-dots"></i>
                    <text id="daily_reply_{{ daily.id }}">{{ daily.reply }}</text>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

<script>
    var DailyClick = function (btn_type, daily_id) {
        var reqInfo = new Common.RequestInfo();
        reqInfo.AddParameter("daily_id", daily_id);
        reqInfo.AddParameter("action", btn_type);

        Common.Ajax('daily/action/', reqInfo, function (rtn) {
            if (rtn.substring(0, 13) == "|||SUCCESS|||") $("#daily_" + btn_type + "_" + daily_id).text(rtn.substring(13));
            else location.href = "user/login";
        }, { 'formMethod': "GET" })
    }

    var LoginCheck = function () {
        var login_id = '{{ request.session.login_id }}';
        if (login_id === '') return false;
        return true;
    }
</script>
{% endblock content %}