studyProject/urls.py
from django.contrib import admin
from django.urls import path, include
from pashion import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "main"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.main, name='main'),
    path('weather/', views.weather, name='weather'),
    path('user/', include('user.urls', namespace="user")),
    path('daily/', include('daily.urls', namespace="daily")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from .views import *
from django.contrib.auth import views as auth_views

app_name = "user"

urlpatterns = [
    path('regist/', Regist.as_view(), name="regist"),
    path('login/', Login.as_view(), name="login"),
    path('logout/', Logout.as_view(), name="logout"),
    path('profile/<str:id>/', Profile.as_view(), name="profile"),
    path('profile_update/', Profile_update.as_view(), name="profile_update")

]

user/models.py
from django.db import models
from django.conf import settings

# 회원 모델

class User(models.Model):
    # ID
    
    id = models.CharField(primary_key=True, max_length=15,null=False)

    # PW
    password = models.CharField(max_length=256, null=True)

    # PW check
    password_chk = models.CharField(max_length=256, null=True)

    # 변경 비밀번호
    newpassword = models.CharField(max_length=256)

    # 가입일
    create_day = models.DateTimeField(auto_now_add=True)

    # 수정일
    update_day = models.DateTimeField(auto_now=True)

    # 핸드폰번호
    phone = models.CharField(max_length=15, null=True, blank=False)

    # 이름
    name = models.CharField(null=False, blank=False, max_length=10)

    # 나이
    birthday = models.CharField(
        null=False, blank=False, max_length=15, default='0000-00-00')

    # 이메일
    email = models.EmailField(null=True, blank=True)

    # 프로필 이미지
    profile_image = models.ImageField(
        null=True, upload_to='images/', blank=True)

    # 닉네임
    nickname = models.CharField(max_length=10, null=False, blank=False)

    # 프로필 설명
    description = models.TextField(null=True, blank=True)

    # 즐겨입는 스타일
    like_style = models.TextField(null=True, blank=True)

    # 유저 타입 (1:일반유저, 99:관리자)
    user_type = models.IntegerField(default=1)

    def __str__(self):
        return self.name + '(' + self.nickname + ')'

user/forms.py
from django import forms
from django.contrib.auth.forms import UserChangeForm
from .models import User



class UserRegistForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['id', 'password', 'password_chk',
                  'name', 'nickname', 'phone', 'email']
        widgets = {
            'nickname': forms.TextInput(attrs={'class': 'form-control', 'placeholder':'15자 이내로 입력 가능합니다.'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'password' : forms.PasswordInput(attrs={'class': 'form-control'}),
        }
        labels = {
            'nickname': '닉네임',
            'email': '이메일',
            'password': '패스워드'
        }          


class UserLoginForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['id', 'password']

class UserEditForm(UserChangeForm):
    password = None        
    phone = forms.CharField(label='연락처', widget=forms.TextInput(
        attrs={'maxlength':'11',}), 
    )        
    name = forms.CharField(label='이름', widget=forms.TextInput(
        attrs={'maxlength':'8',}), 
    )        
    nickname = forms.CharField(label='닉네임', widget=forms.TextInput(
        attrs={'maxlength':'10',}), 
    )
    description = forms.CharField(label='자기소개', widget=forms.Textarea(
        attrs={'maxlength':'100',}), 
    )
    class Meta:
        model = User
        fields = ['phone', 'name', 'nickname', 'description']

user/views.py
import json
from django.views import View
from django.http import JsonResponse
from django.shortcuts import *
from .models import User
from django.contrib import messages
from .forms import *
from .forms import UserEditForm
from datetime import datetime
from django.contrib.auth import authenticate
from django.conf import settings
from studyProject.util import *
from studyProject.common import *
from studyProject.decorate import *

# Create your views here.

crypt = SimpleEnDecrypt()


class Regist(View):
    def post(self, request):
        data = request.POST
        form = UserRegistForm(data)

        if User.objects.filter(id=data['id']).exists():
            return render(request, 'user/regist.html', {'form': form, 'id': 'is-invalid'})

        if data['password'] != data['password_chk']:
            return render(request, 'user/regist.html', {'form': form, 'password': 'is-invalid'})

        if form.is_valid():
            # 저장 전 비밀번호 및 이메일 암호화 작업
            post = form.save(commit=False)
            post.password = crypt.encrypt(data['password'])
            post.password_chk = crypt.encrypt(data['password_chk'])
            post.email = crypt.encrypt(data['email'])
            post.save()

            form = UserLoginForm()
            return render(request, 'user/login.html', {'form': form, 'regist': True})
        else:
            return render(request, 'user/regist.html', {'form': form})

    def get(self, request):
        form = UserRegistForm()
        return render(request, 'user/regist.html', {'form': form})


class Login(View):
    form = UserLoginForm()

    def post(self, request):
        data = request.POST
        self.form = UserLoginForm(data)

        if User.objects.filter(id=data['id']).exists():
            password = crypt.decrypt(
                User.objects.filter(id=data['id'])[0].password)

        if User.objects.filter(id=data['id']).exists() and password == data['password']:
            request.session['login_id'] = data['id']
            return redirect("/")
        else:
            return render(request, 'user/login.html', {'form': self.form})

    def get(self, request):
        login_id = request.session.get('login_id', None)
        if login_id is not None and User.objects.filter(id=login_id).exists():
            return render(request, 'main.html')
        return render(request, 'user/login.html', {'form': self.form})


# login required
class Logout(View):
    @LoginAuth
    def get(self, request):
        request.session.pop('login_id')
        return redirect("/")


class Profile(View):
    @LoginAuth
    def get(self, request, id):
        user = User.objects.get(id=id)
        user.email = crypt.decrypt(user.email)
        return render(request, 'user/profile.html', {'user': user})


class Profile_update(View):
    @LoginAuth
    def post(self, request):
        login_id = request.session.get('login_id', None)
        user = User.objects.get(id=login_id)
        form = UserEditForm(request.POST, instance=user)
        print("form_isvalid = " + str(form.is_valid()))
        if form.is_valid():
            post = form.save(commit=False)
            post.name = form.cleaned_data['name']
            post.nickname = form.cleaned_data['nickname']
            post.phone = form.cleaned_data['phone']
            post.description = form.cleaned_data['description']
            post.save()
            form = UserEditForm()
        return render(request, 'user/profile.html', {'form': form, 'user': user})

    def get(self, request):
        login_id = request.session.get('login_id', None)
        user = User.objects.get(id=login_id)
        user_change_form = UserEditForm(instance=user)
        return render(request, 'user/profile_update.html', {'user_change_form': user_change_form, 'user': user})


class DailyLike(View):
    @LoginAuth
    def get(request):
        return render(request, 'daily/like.html')

user/templates/user/login.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
	<form method="post" class="post-form" action="{% url 'user:login' %}">
		{% csrf_token %}

		{% if regist %}
		<div class="alert alert-primary">
			회원가입이 완료되었습니다.
		</div>
		{% endif %}

		<div class="form-group">
			<label for="username">사용자ID</label>
			<input type="text" class="form-control" name="id" id="id" value="{{ form.id.value|default_if_none:'' }}">
		</div>
		<div class="form-group">
			<label for="password">비밀번호</label>
			<input type="password" class="form-control" name="password" id="password"
				value="{{ form.password.value|default_if_none:'' }}">
		</div>

		{% if form.errors %}
		<p class="text-danger">아이디 또는 비밀번호를 확인해주세요.</p>
		{% endif %}
		<br>
		<button type="submit" class="btn btn-outline-info btn-block float-left rounded">로그인</button>
	</form>
</div>
{% endblock content %}

user/templates/user/profile.html
{% extends "base.html" %}
<meta name="viewport" content="width=550, user-scalable=yes">
{% block content %}

<div class="container">
    <div style="margin-top: 5rem !important;">
        <div class="col-12">

            <div class="row justify-content-center">
                <div class="card">
                    <div class="card-header" style="padding-bottom:8px;">
                        <strong style="font-size: 18px;"><i class="fas fa-user-cog"></i>&nbsp;&nbsp;내 정보</strong>
                    </div>
                    <div class="card-body">
                        <table style="color:black; margin-left:10px;">
                            <tr>
                                <td class="profile_title">아이디</td>
                                <td class="profile_content">{{ user.id }}</td>

                            </tr>
                            <tr>
                                <td class="profile_title">이름</td>
                                <td class="profile_content">{{ user.name }}</td>
                            </tr>
                            <tr>
                                <td class="profile_title">이메일</td>
                                <td class="profile_content">{{ user.email }}</td>
                            </tr>
                            <tr>
                                <td class="profile_title">닉네임</td>
                                <td class="profile_content">{{ user.nickname }}</td>
                            </tr>
                            <tr>
                                <td class="profile_title">연락처</td>
                                <td class="profile_content">{{ user.phone }}</td>
                            </tr>
                            <tr>
                                <td class="profile_title">자기소개</td>
                                <td class="profile_content">{{ user.description }}</td>
                            </tr>
                        </table>

                        <hr>
                        {% if user.id == request.session.login_id %}
                        <div style="text-align: center;">
                            <a href="{% url 'user:profile_update' %}" style="color:#d14040f2; font-size:15px;"><i
                                    class="fas fa-user-edit"></i>&nbsp;내정보수정</a>&nbsp;&middot;&nbsp;
                        </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

user/templates/user/profile_update.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <div style="margin-top: 5rem !important;">
        <div class="col-12">

            <div class="row justify-content-center">
                <div class="card">
                    <div class="card-header" style="padding-bottom:8px;">
                        <strong style="font-size: 18px;"><i class="fas fa-user-edit"></i>&nbsp;&nbsp;내 정보수정</strong>
                    </div>
                    <div class="card-body">
                        <form method="POST">
                            {% csrf_token %}
                            <table style="color:black; margin-left:10px;">
                                <tr>
                                    <td class="profile_title">아이디</td>
                                    <td class="profile_content">{{ user.id }}</td>
                                </tr>
                                <tr>
                                    <td class="profile_title">이름</td>
                                    <td class="profile_content">{{ user_change_form.name }}</td>
                                </tr>
                                <tr>
                                    <td class="profile_title">연락처</td>
                                    <td class="profile_content">{{ user_change_form.phone }}</td>
                                </tr>
                                <tr>
                                    <td class="profile_title">닉네임</td>
                                    <td class="profile_content">{{ user_change_form.nickname }}</td>
                                </tr>
                                <tr>
                                    <td class="profile_title">자기소개</td>
                                    <td class="profile_content">{{ user_change_form.description }}</td>
                                </tr>
                            </table>

                            <br>
                            <div style="text-align: center; margin-bottom:-15px;">
                                <a onclick="location.href='/user/profile/'" class="btn btn-sm" id="back_btn"><i
                                        class="fa fa-reply"></i>&nbsp;돌아가기</a>
                                <button type="submit" class="btn btn-sm" id="detail_btn"><i
                                        class="fas fa-check"></i>&nbsp;수정하기</button>
                            </div>
                        </form>

                        <script type="text/javascript">
                            function maxLengthCheck(object) {
                                if (object.value.length > object.maxLength) {
                                    object.value = object.value.slice(0, object.maxLength);
                                }
                            }
                        </script>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

user/templates/user/regist.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
	<form method="post" class="post-form" action="{% url 'user:regist' %}">
		{% csrf_token %}

		<div class="form-group">
			<label for="username">
				사용자ID
				{% if id %}
				<text class="text-danger">(사용 중인 아이디 입니다)</text>
				{% endif %}
			</label>

			<input type="text" class="form-control {{ id|default:'is-invalid' }}" name="id" id="id"
				value="{{ form.id.value|default:'' }}">
		</div>

		<div class="form-group">
			<label for="password">
				비밀번호
				{% if password %}
				<text class="text-danger">(비밀번호가 서로 일치하지 않습니다.)</text>
				{% endif %}
			</label>

			<input type="password" class="form-control {{ password|default:'is-invalid' }}" name="password"
				id="password" value="{{ form.password.value|default:'' }}">
		</div>

		<div class="form-group">
			<label for="password_chk">비밀번호 확인</label>

			<input type="password" class="form-control {{ password|default:'is-invalid' }}" name="password_chk"
				id="password_chk" value="{{ form.password_chk.value|default:'' }}">
		</div>

		<div class="form-group">
			<label for="name">
				이름
				{% if form.name.value == '' %}
				<text class="text-danger">(이름을 입력해주세요.)</text>
				{% endif %}
			</label>
			<input type="text" class="form-control {{ form.name.value|default:'is-invalid' }}" name="name" id="name"
				value="{{ form.name.value|default:'' }}">
		</div>

		<div class="form-group">
			<label for="phone">
				전화번호
				{% if form.phone.value == '' %}
				<text class="text-danger">(전화번호를 입력해주세요.)</text>
				{% endif %}
			</label>
			<input type="text" class="form-control {{ form.phone.value|default:'is-invalid' }}" name="phone" id="phone"
				value="{{ form.phone.value|default:'' }}">
		</div>

		<div class="form-group">
			<label for="email">
				이메일
				{% if form.email.value == '' %}
				<text class="text-danger">(이메일을 입력해주세요.)</text>
				{% endif %}
			</label>
			<input type="text" class="form-control {{ form.email.value|default:'is-invalid' }}" name="email" id="email"
				value="{{ form.email.value|default:'' }}">
		</div>
		<div class="form-group">
			<label for="nickname">
				닉네임
				{% if form.nickname.value == '' %}
				<text class="text-danger">(닉네임을 입력해주세요.)</text>
				{% endif %}
			</label>
			<input type="text" class="form-control {{ form.nickname.value|default:'is-invalid' }}" name="nickname"
				id="nickname" value="{{ form.nickname.value|default:'' }}">
		</div>
		<br>
		<button type="submit" class="btn btn-outline-info btn-block float-left rounded">회원가입</button>
	</form>
</div>
{% endblock content %}